= Asciidoc SSCPfootnote:[Summary of safety and clinical performance] (MDCGfootnote:[Medical Device Coordination Group]) Project Template

[abstract]
Asciidoc project template for the CCS (component content) production of SSCP (MDCG-2019) documentation in medical manufacturing contexts.

== General

Traditional XML-based publication technologies do not align with modern DaCfootnote:[Docs-As-Code] process, infrastructure, and management. XML-based publications also require thick, expensive, and complex tooling for writing, review, and publishing.

At the same time, XML-based tooling is often sought after for the possibility of content re-use via CCSfootnote:[Component Content System] techniques, and the powerful validation mechanisms.

Asciidoc provides a middle path: it opens up simple CCS techniques but can also be used in conjunction with both DaC process and standard open toolingfootnote:[git, visual studio code, intellij, etc].

This project is a placeholder for the generation of SSCP publications using an Asciidoc / DaC process.

== Usage

NOTE: More complex change management techniques - like aggregating change packages into a document revision via git tagging, autogen revision history/list of changes, etc - is outside of the scope of this README.

[.procedure]
. Project planning teams identify which of the sections of the SSCP are required for the current context.
. Relevant sections are assigned to individual writers. 
+
NOTE: In the git context, this can be handled via branching.
. The writer teams work on their sections.
. When the writer team is finished with their section, Pull Request against the master / root, and assign the PR to the reviewer. 
. The PR is either accepted or rejected. 
.. If rejected, the PR comments will be sent back to the writer team
.. If accepted, the writer contribution is assimilated into the master
. When all writer teams are complete, the SSCP is ready for the next stage of acceptannce
. Run the desired PMC publication to assimilate the modules into the publication.
+
NOTE: Each PMC assembles the components into a unified SSCP document.

== About the File System

.Folder Name Description
[horizontal]
DMC:: Data Modules, representing content modules that can be combined into new SSCP documents. Accessed from PMC via https://docs.asciidoctor.org/asciidoc/latest/directives/include/[Asciidoc include directive]
PMC:: Publication Modules, each of which can produce a specific SSCP document. PMs use the `include` directive to pull in Data Modules. 
GFX:: Supporting graphics in raster format
SVG:: Supporting graphics in vector format
CIR:: Common Information Repository, each of which provide a warehouse of re-usable admonitions, material safety data, and/or other discrete parts. Accessed from DMC via https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/[Asciidoc include to tagged region]
XSL:: Stylesheets using the DocBook-XSL PDF pipeline. This is the current active PDF pipeline desired by the client.
YML:: Stylesheets using the `asciidoctor-pdf` PDF publishing pipeline.
PMM:: Stylesheets using the `asciidoctor-web-pdf` (JS+CSS Paged Media Module) PDF publishing pipeline.

== More information

https://health.ec.europa.eu/document/download/5f082b2f-8d51-495c-9ab9-985a9f39ece4_en[MDCG 2019]
